In [6]:
import numpy as np
list=['Niti',5,'Riya',100]
print(list)
print(list[0])
print(list[2])
print(list[3])

['Niti', 5, 'Riya', 100]
Niti
Riya
100


In [13]:
   import numpy as np
   a=np.zeros(5)
   b=np.ones(3)
   c=np.arange(4)
   d=np.arange(1,10)   
   e=np.arange(1,4,2)
   print(a)
   print(b)
   print(c)
   print(d)
   print(e)

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0 1 2 3]
[1 2 3 4 5 6 7 8 9]
[1 3]


In [16]:
   import numpy as np
   arr1=np.array([[1,2,3],['a','b','c']])
   zeros=np.zeros((4,4))
   twos=np.ones((2,2),dtype='int')  
   
   print(arr1)
   print(zeros)
   print(twos)

[['1' '2' '3']
 ['a' 'b' 'c']]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1]
 [1 1]]


In [17]:
 print(arr1.ndim)

2


In [23]:
 import numpy as np
 ar1=np.array([2,2,3])
 ar2=np.array([1,5,3])
 q=ar1+ar2
 w=ar1-ar2
 e=ar1/ar2
 print(ar1)
 print(ar2)
 print(q) 
 print(w) 
 print(e)
 print("Add 4 to all elements:",q+4)
 print("Subtracting 3 from all elements:",w-1)

[2 2 3]
[1 5 3]
[3 7 6]
[ 1 -3  0]
[2.  0.4 1. ]
Add 4 to all elements: [ 7 11 10]
Subtracting 3 from all elements: [ 0 -4 -1]


In [28]:
import numpy as np
list=['Niti',5,'Riya',100,55]
ar3=np.array([[1, 2, 3], [6, 7, 8],[4,5,6]])
print(list[0])
print(list[0:4])
print(list[-1])
print(list[2:])
print(list[-2:])
print(ar3[1,2:])
print(ar3[1:2,1])



Niti
['Niti', 5, 'Riya', 100]
55
['Riya', 100, 55]
[100, 55]
[8]
[7]


In [29]:
   print(ar3.shape)
   
  

(3, 3)


In [34]:
import numpy as np
csv = np.genfromtxt('Latest Covid-19 India Status.csv', delimiter=",")
print('No of dimensions of the array:',csv.ndim)     
print('Total no of elements of the array:',csv.size)
print('Shape of the array:',csv.shape)
x = np.where(csv ==1.71 )
y = np.where(csv == 'Kerala')
print(x)
print(y)


No of dimensions of the array: 2
Total no of elements of the array: 296
Shape of the array: (37, 8)
(array([ 1, 13], dtype=int64), array([7, 7], dtype=int64))
(array([], dtype=int64),)


<ipython-input-34-84835fc5e6c9>:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  y = np.where(csv == 'Kerala')


In [41]:
from scipy import stats
import numpy as np
arr=np.array([129,13241,213,5114,9637,809,13511,4,25041,3126])
x=np.mean(arr)
y=np.median(arr)
z=stats.mode(arr)
w=np.std(arr)
print(x)
print(y)
print(z)
print(w)

7082.5
4120.0
ModeResult(mode=array([4]), count=array([1]))
7828.269083903542


In [4]:
import pandas as pd
import numpy as np
data = np.array(['a','e',3,6])
ser=pd.Series(data)
ser1=pd.Series(data,index=[1, 2, 3, 4])
print(ser[:2])
print(ser1[2])


0    a
1    e
dtype: object
e


In [24]:
import pandas as pd    
df = pd.read_csv('Latest Covid-19 India Status.csv')     
ser = pd.Series(df['State/UTs']) 
data1 = pd.Series(ser,index=['a', 'b', 'd', 'e'])
data = ser.head(5)
print(data)
data1 = ser.head(4)
print(data1)


0    Andaman and Nicobar
1         Andhra Pradesh
2      Arunachal Pradesh
3                  Assam
4                  Bihar
Name: State/UTs, dtype: object
0    Andaman and Nicobar
1         Andhra Pradesh
2      Arunachal Pradesh
3                  Assam
Name: State/UTs, dtype: object


In [19]:
import pandas as pd    
data = pd.read_csv("Latest Covid-19 India Status.csv") 
before = data.dtypes 
data["State/UTs"]= data["State/UTs"].astype(str) 
data["Active"]= data["Active"].astype(float)
after = data.dtypes 
print("BEFORE CONVERSION\n", before, "\n") 
print("AFTER CONVERSION\n", after, "\n") 


BEFORE CONVERSION
 State/UTs               object
Total Cases              int64
Active                   int64
Discharged               int64
Deaths                   int64
Active Ratio (%)       float64
Discharge Ratio (%)    float64
Death Ratio (%)        float64
dtype: object 

AFTER CONVERSION
 State/UTs               object
Total Cases              int64
Active                 float64
Discharged               int64
Deaths                   int64
Active Ratio (%)       float64
Discharge Ratio (%)    float64
Death Ratio (%)        float64
dtype: object 



In [20]:
import pandas as pd    
data = pd.read_csv("Latest Covid-19 India Status.csv") 
before = data.dtypes 
dtype_before = type(data["Active"]) 
Active_list = data["Active"].tolist() 
dtype_after = type(Active_list)
print("Data type after/n",dtype_after)
print("Data type before/n",dtype_before)
print(Active_list)

Data type after/n <class 'list'>
Data type before/n <class 'pandas.core.series.Series'>
[14, 22358, 4465, 15726, 530, 32, 2789, 48, 587, 1238, 342, 740, 931, 1319, 276, 23928, 1386262, 68, 81, 149, 96833, 10251, 4708, 7772, 1312, 17201, 922, 771, 328, 2849, 24025, 9625, 3934, 932, 611, 11891]


In [35]:
import pandas as pd
data = pd.read_csv("Latest Covid-19 India Status.csv", index_col ="State/UTs")
data1=pd.read_csv("Latest Covid-19 India Status.csv")
print(data1[['Active']])
first = data.loc["Goa"]
second = data.loc["Kerala"]
first1= data["Discharged"]
print(first1)
print(first, "\n\n\n", second)

     Active
0        14
1     22358
2      4465
3     15726
4       530
5        32
6      2789
7        48
8       587
9      1238
10      342
11      740
12      931
13     1319
14      276
15    23928
16  1386262
17       68
18       81
19      149
20    96833
21    10251
22     4708
23     7772
24     1312
25    17201
26      922
27      771
28      328
29     2849
30    24025
31     9625
32     3934
33      932
34      611
35    11891
Total Cases            61922.00
Active                    32.00
Discharged             61081.00
Deaths                   809.00
Active Ratio (%)           0.05
Discharge Ratio (%)       98.64
Death Ratio (%)            1.31
Name: Chandigarh, dtype: float64
State/UTs
Andaman and Nicobar                            7382
Andhra Pradesh                              1916914
Arunachal Pradesh                             41025
Assam                                        536597
Bihar                                        714223
Chandigarh                   

In [39]:
import pandas as pd
data = pd.read_csv("Latest Covid-19 India Status.csv", index_col ="State/UTs")
row7 = data.iloc[5]  
print(row7)

Total Cases            61922.00
Active                    32.00
Discharged             61081.00
Deaths                   809.00
Active Ratio (%)           0.05
Discharge Ratio (%)       98.64
Death Ratio (%)            1.31
Name: Chandigarh, dtype: float64


In [42]:
import pandas as pd
data = pd.read_csv("Latest Covid-19 India Status.csv", index_col ="State/UTs")
data.isnull()
data.fillna(5)
data.dropna()

Total Cases   Active  Discharged  \
State/UTs                                                                    
Andaman and Nicobar                              7525       14        7382   
Andhra Pradesh                                1952513    22358     1916914   
Arunachal Pradesh                               45703     4465       41025   
Assam                                          557437    15726      536597   
Bihar                                          724390      530      714223   
Chandigarh                                      61922       32       61081   
Chhattisgarh                                  1001037     2789      984737   
Dadra and Nagar Haveli and Daman and Diu        10637       48       10585   
Delhi                                         1435844      587     1410216   
Goa                                            170416     1238      166052   
Gujarat                                        824683      342      814265   
Haryana                                        769717      740      759360   
Himachal Pradesh                               205017      931      200573   
Jammu and Kashmir                              320491     1319      314798   
Jharkhand                                      346918      276      341518   
Karnataka                                     2893556    23928     2833276   
Kerala                                        3254064  1386262     3099469   
Ladakh                                          20296       68       20021   
Lakshadweep                                     10127       81        9997   
Madhya Pradesh                                 791738      149      781077   
Maharashtra                                   6258079    96833     6029817   
Manipur                                         91460    10251       79744   
Meghalaya                                       60597     4708       54875   
Mizoram                                         31145     7772       23238   
Nagaland                                        27240     1312       25390   
Odisha                                         965715    17201      943069   
Puducherry                                     120227      922      117518   
Punjab                                         598741      771      581712   
Rajasthan                                      953522      328      944242   
Sikkim                                          24823     2849       21644   
Tamil Nadu                                    2546689    24025     2488775   
Telengana                                      640659     9625      627254   
Tripura                                         76315     3934       71642   
Uttar Pradesh                                 1708152      932     1684471   
Uttarakhand                                    341673      611      333703   
West Bengal                                   1522833    11891     1492878   

                                          Deaths  Active Ratio (%)  \
State/UTs                                                            
Andaman and Nicobar                          129              0.19   
Andhra Pradesh                             13241              1.15   
Arunachal Pradesh                            213              9.77   
Assam                                       5114              2.82   
Bihar                                       9637              0.07   
Chandigarh                                   809              0.05   
Chhattisgarh                               13511              0.28   
Dadra and Nagar Haveli and Daman and Diu       4              0.45   
Delhi                                      25041              0.04   
Goa                                         3126              0.73   
Gujarat                                    10076              0.04   
Haryana                                     9617              0.10   
Himachal Pradesh                            3513              0.45   
Jammu and Kashmir          

In [45]:
import pandas as pd
dict = {'Name':["Afiat", "Niti", "Maruf", "Rafia"], 'Degree': ["B.sc", "B.sc", "B.sc", "B.sc"]}
data=pd.DataFrame(dict)
print(data)
 

    Name Degree
0  Afiat   B.sc
1   Niti   B.sc
2  Maruf   B.sc
3  Rafia   B.sc
